name: lint

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: clone the repo
      uses: actions/checkout@v3

    - name: install dependencies
      run: npm install

    - name: run eslint
      run: npm run lint
